### ISSUE TITLE
Fields data handling: avoid mutating value prop

### ISSUE THREAD

**Issue by distantnative** [k-next/ui#61]
Currently `value` is used as simple prop on fields to pass content data to the component in the future. However, Vue does not allow mutating a prop directly. We have to find another solution for this.

**Comment by fourpixels** [comment]
What about `.sync` modifier?

https://vuejs.org/v2/guide/components.html#sync-Modifier

**Comment by distantnative** [comment]
Thanks for pointing that out.

But we would still need to define `value` e.g. in `data()` instead as prop, am I correct?
And this would cause the headache, that we would want to be able to pass the content data value like

```
<kirby-some-field value="test"></kirby-some-field>
```

So we would need then to work with some alias internally in the component:

```
data() {
  return {
     _value: this.value
  }
}
```

Or is there a more elegant way?

**Comment by fourpixels** [comment]
Well basically you want to pass an actual property to the child, which will be used as a value (to be displayed for example), and this child should be able to mutate this property. This breaks the whole concept of Vue and it's components, and there's no "simple workaround".

So yes, you should use internal data variable to store child component's state, which can be set on creation to be equal to the property provided, as well as use events to propagate synchronization with parent property, on child state update. Which sounds good to me - I mean there won't be much code bloat.
Also more complex components that you're talking about should use some kind of de/serialization of that data when setting/mutating it - like date, time, email, select? tags?  - they consist of multiple sub-components that cannot be automatically populated with values, or need calculations in order to mutate.

Maybe you could provide samples of where this is too much of a hassle, possibly simple inputs like checkbox?

P.S.
I've found another thing that _might_ be helpful but haven't really thought nor tested it -
 customizing the way `v-model` works: https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model

**Comment by fourpixels** [comment]
I've checked a code that we have and it looks like this:

main.vue:
```vue
<div>
  <group :groups.sync="groups"></group> <!-- groups will be two-way binded -->
</div>
```


group.vue:
```vue
<template>
  <div>
    <div v-for="g in groups">
      <input type="checkbox" :value="g.id" v-model="ids">{{ g.name }}
    </div>
  </div>
</template>
<script>
  export default {
    name: "group",
    props: ['groups'],
    data() {
      return {
        ids: this.groups // link to props
      }
    },
    watch: {
      ids () {
        this.$emit('update:groups', this.ids); // bubble update up
      }
    }
  }
</script>
```

So yeah, there's additional code very similar to what you've suggested. *But* keep in mind that this is a list of checkboxes. If you simply want to update a checkbox then you can easily do something like:

```vue
<custom-checkbox :value="dynamic" @change="value => { dynamic= value }" ></custom-checkbox>
```

All you have to do is to emit event from the `custom-checkbox` and it will work like a charm :)
